### ISSUE TITLE
Cannot compile Shaders

### ISSUE THREAD

**Issue by grothe6** [smealum/ludum34#3]
Hi Smea,

I try to run this on Intel HD 3000 internal graphics.
The error is the following:

```
[INFO] (texture.cpp:19) loading texture : font.png
[INFO] (shader.cpp:138) Shader shaders/stars.gsh compiled successfully.
[INFO] (shader.cpp:138) Shader shaders/stars.fsh compiled successfully.
[INFO] (shader.cpp:138) Shader shaders/stars.vsh compiled successfully.
[INFO] (audio.cpp:46) loading sound : cubemove.wav
[INFO] (audio.cpp:46) loading sound : endpulse.wav
[ERROR] (shader.cpp:131: errno: None) Impossible de compiler le shader : shaders/cube.gsh
[ERROR] (shader.cpp:132: errno: None)

ERROR: 0:24: 'flat' : syntax error syntax error
```

It was a great stream!!
Cheers
Thecamper

**Comment by lukestrong** [comment]
Also using Intel HD 3000 internal graphics, same error :/

**Comment by Steveice10** [comment]
Your GPU/driver doesn't seem to support the 'flat' qualifier in GLSL.

**Comment by ghost** [comment]
Same error.
I can play crysis with this craptop but not smea's little indie game. Good grief.

**Comment by smealum** [comment]
can you all report your graphics card (and driver version if possible) ?

it's possible that i'm using shader features that your computers don't support unfortunately. this all relies on opengl 3.3 shader stuff.

**Comment by grothe6** [comment]
Intel HD 3000 with Driver v.9.17.10.4229

As Steveice10 and someone on the twitch chat pointed out, it's probably that the graphics card doesn't support OpenGL 3.3.

**Comment by ghost** [comment]
Intel HD 3000 as well.
9.17.10.4229

**Comment by partlyblue** [comment]
Intel HD 3000, Driver v.9.17.10.4229.
I am starting to see a trend...

**Comment by ghost** [comment]
Smea hates antiquated hardware which is surprising given his affinity for Nintendo handhelds. lol
