### ISSUE TITLE
Game is too good

### ISSUE THREAD

**Issue by byteandahalf** [smealum/ludum34#8]
DIS GAME DANK ASF PLZ FIX

**Comment by slice** [comment]
SHHHH. No spam.

**Comment by 143mailliw** [comment]
politely fuck off

**Comment by smealum** [comment]
thank you for your input

it is much appreciated

**Comment by byteandahalf** [comment]
No, thank YOU for dis dank game

**Comment by ghost** [comment]
:o byteandahalf
